Excluding a class that surefire is believing to be a test to run...
Only 2 errors left while running $ mvn test, and they have the same cause:

org.xml.sax.SAXParseException: The prefix "xsi" for attribute "xsi:noNamespaceSchemaLocation" associated with an element type "ruleset" is not bound.

almost there :)

git-svn-id: https://pmd.svn.sourceforge.net/svnroot/pmd/trunk@6094 51baf565-9d33-0410-a72c-fc3788e3496d